require 'rbconfig'
require_relative '../dvlp.rb'

PROJECT_DIR = File.expand_path("..",Dir.pwd)
VENDOR_DIR = "#{PROJECT_DIR}/vendor"

BUILD_DIR = "build"
CLASSES_DIR = "#{BUILD_DIR}/classes"

DEPENDENCIES_DIR = ""

TARGET_DIR = "#{PROJECT_DIR}/target"

jars = Dir["#{VENDOR_DIR}/*.jar"]

unless RUBY_PLATFORM == 'java'
  abort 'Please run with JRuby'
end

#-----------------------------------------------------------------------------------------
desc 'Compile java classes'
task :compile do

  classes    = Dir['**/*.java']
  sh "javac -classpath #{jars.join(';')} -d #{CLASSES_DIR} #{classes.join(' ')}"

end

#-----------------------------------------------------------------------------------------
desc 'Make jar file'
task :jar do

  Dir.chdir("build/classes")
  classes = Dir['**/*.class']
  p classes
  sh "jar -cf #{TARGET_DIR}/helper.jar #{classes.join(' ')}"

end

#-----------------------------------------------------------------------------------------
desc 'Clean files'
task :clean do
  
  files = Dir['**/*.class']
  p "#{files.join(' ')}"
  
end
