require_relative '../config.rb'

dirs = SciCom.vendor_dir.split(";")
dirs << SciCom.project_dir + "/" + "MDArray" + "/vendor"
p dirs
jars = Array.new 
dirs.each do |dir|
  jars << Dir[dir + "/*.jar"]
end

unless RUBY_PLATFORM == 'java'
  abort 'Please run with JRuby'
end

#-----------------------------------------------------------------------------------------
desc 'Compile java classes'
task :compile do
  classes    = Dir['**/*.java']
  sh "javac -classpath #{jars.join(';')} -d #{SciCom.classes_dir} #{classes.join(' ')}"
end

#-----------------------------------------------------------------------------------------
desc 'Make jar file'
task :jar do

  Dir.chdir("build/classes")
  classes = Dir['**/*.class']
  sh "jar -cf #{SciCom.target_dir}/helper.jar #{classes.join(' ')}"

end

#-----------------------------------------------------------------------------------------
desc 'Clean files'
task :clean do
  
  files = Dir['**/*.class']
  p "#{files.join(' ')}"
  
end
